language: c

sudo: false

addons:
  apt:
    packages:
      - doxygen

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

script:
  - build_platform uno
  - doxygen

notifications:
  email:
    on_success: change
    on_failure: change
